"use client";

import { Container, Divider, Stack, Title, Text, Group, Anchor, Tooltip, ThemeIcon } from "@mantine/core";
import { IconBrandMantine, IconBrandNextjs, IconBrandReact, IconBrandTypescript } from "@tabler/icons-react";
import React from "react";

function Page() {
  return (
    <Container>
      <Stack>
        <Title size="h1">
          Projects
        </Title>
        <Divider />
        <Text>This is where I will put projects I have worked on when I have time. There are also a lot more projects listed in {" "}
          <Anchor href="/Education">education</Anchor> but those are school projects. Finally, I have also spent a lot of time working on big projects
          through school clubs and research. Those are mentioned in {" "} <Anchor href="/ExperiencesAndCareer">experiences.</Anchor>
        </Text>
        <Group>
          <Title size="h2">
            Portfolio
          </Title>
          <Tooltip label="Next.js">
            <ThemeIcon variant="light">
              <IconBrandNextjs />
            </ThemeIcon>
          </Tooltip>
          <Tooltip label="React.js">
            <ThemeIcon variant="light">
              <IconBrandReact />
            </ThemeIcon>
          </Tooltip>
          <Tooltip label="TypeScript">
            <ThemeIcon variant="light">
              <IconBrandTypescript />
            </ThemeIcon>
          </Tooltip>
          <Tooltip label="Mantine">
            <ThemeIcon variant="light">
              <IconBrandMantine />
            </ThemeIcon>
          </Tooltip>
        </Group>
        <Text>
          This is the site you&apos;re looking at! It is built entirely using Next.js and React.
        </Text>
        <Text>
          Initially I wanted to try learning Rust so I spun up a simple webserver in Rust using the Actix library,
          and used it to serve js bundles generated by Vite.
          I had set up middleware, CORS, etc in my Rust server but then I realized I would have to do a lot of styling
          manually. This would involve a lot of CSS. I was feeling pretty lazy at the time so this is where I gave up on that approach.
          I then switched to Next.js and Mantine because I would have to do very little styling work on my own.
        </Text>
        <Text>
          Next.js and Mantine and both much easier to setup and use compared to my Rust approach and saved me a lot of time.
          I had less fun than when I was using Rust but I also got this site mostly written in ~half the time it might&apos;ve taken me in Rust.
        </Text>
      </Stack>
    </Container>
  );
}

export default Page;
